version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      release:
        patterns:
          - "yummacss"
          - "@yummacss/api"
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "build"
      include: "scope"
