import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { rootDir } from "./helpers";

/**
 * `src/registry/index.ts` is generated by `scripts/generate-registry.mjs` and
 * carries a "do NOT edit this file manually" banner. Nothing enforced that.
 *
 * Adding a component to `src/registry/ui/` without regenerating is silent: the
 * file builds, the component is unreachable, and `<ComponentPreview>` renders
 * nothing at all rather than erroring. These are the checks that make
 * forgetting loud, in the same spirit as `scripts/check-sidebar.mjs`.
 */

const registryDir = join(rootDir, "src/registry/ui");
const indexPath = join(rootDir, "src/registry/index.ts");

function componentFiles(): string[] {
  return readdirSync(registryDir)
    .filter((file) => file.endsWith(".tsx") || file.endsWith(".ts"))
    .map((file) => file.replace(/\.tsx?$/, ""))
    .sort();
}

function mappedIds(): string[] {
  const source = readFileSync(indexPath, "utf-8");
  return [...source.matchAll(/^\s*"([^"]+)":\s*\(\)\s*=>\s*import\(/gm)].map(
    (match) => match[1],
  );
}

describe("Yumma UI registry", () => {
  it("maps every component file", () => {
    const missing = componentFiles().filter(
      (id) => !new Set(mappedIds()).has(id),
    );

    expect(
      missing,
      "run `node scripts/generate-registry.mjs` to pick these up",
    ).toEqual([]);
  });

  it("does not map components that no longer exist", () => {
    const files = new Set(componentFiles());
    const stale = mappedIds().filter((id) => !files.has(id));

    expect(
      stale,
      "run `node scripts/generate-registry.mjs` to drop these",
    ).toEqual([]);
  });

  it("has no duplicate ids", () => {
    const ids = mappedIds();
    const seen = new Set<string>();
    const duplicates = ids.filter((id) => !seen.add(id));

    expect(duplicates).toEqual([]);
  });

  it("points every id at its own file", () => {
    const source = readFileSync(indexPath, "utf-8");
    const mismatched = [
      ...source.matchAll(
        /^\s*"([^"]+)":\s*\(\)\s*=>\s*import\("\.\/ui\/([^"]+)"\)/gm,
      ),
    ]
      .filter(([, id, target]) => id !== target)
      .map(([, id, target]) => `${id} -> ${target}`);

    expect(mismatched).toEqual([]);
  });

  it("is not empty", () => {
    expect(mappedIds().length).toBeGreaterThan(0);
  });
});
