import type { Template } from "./types";

export const templates: Template[] = [
  {
    slug: "neutra",
    name: "Neutra",
    tagline: "Design Agency",
    description:
      "A minimal landing page template built for design agencies and studios.",
    price: 19,
    currency: "EUR",
    status: "available",
    templateVersion: "1.0.0",
    frameworks: [
      { name: "Next.js", version: "16" },
      { name: "React", version: "19" },
    ],
    stack: ["Next.js 16", "React 19", "Yumma CSS 3", "Phosphor Icons"],
    version: "3.7.0",
    pages: [
      { path: "/src/app/page.tsx", title: "Home" },
      { path: "/src/app/about/page.tsx", title: "About" },
      { path: "/src/app/services/page.tsx", title: "Services" },
      { path: "/src/app/work/page.tsx", title: "Work" },
      { path: "/src/app/portfolio/page.tsx", title: "Portfolio" },
      { path: "/src/app/pricing/page.tsx", title: "Pricing" },
      { path: "/src/app/process/page.tsx", title: "Process" },
      { path: "/src/app/not-found.tsx", title: "404 page" },
    ],
    previewUrl: "#",
    purchaseUrl: "#",
    cover: "/img/templates/neutra/preview.png",
    screenshots: [
      "/img/templates/neutra/home.png",
      "/img/templates/neutra/pricing.png",
      "/img/templates/neutra/process.png",
      "/img/templates/neutra/work.png",
    ],
  },
  {
    slug: "ariake",
    name: "Ariake",
    tagline: "Developer Portfolio",
    description:
      "A dark, code-focused portfolio template for developers and engineers.",
    price: 19,
    currency: "EUR",
    status: "coming-soon",
    templateVersion: "1.0.0",
    frameworks: [
      { name: "Next.js", version: "16" },
      { name: "React", version: "19" },
    ],
    stack: ["Next.js 16", "React 19", "Yumma CSS 3", "Phosphor Icons"],
    version: "3.7.0",
    pages: [],
    previewUrl: "#",
    purchaseUrl: "#",
    cover: "/img/templates/placeholder.png",
    screenshots: [],
  },
  {
    slug: "lumiar",
    name: "Lumiar",
    tagline: "SaaS Landing",
    description:
      "A bright, conversion-focused landing page for SaaS products and startups.",
    price: 19,
    currency: "EUR",
    status: "coming-soon",
    templateVersion: "1.0.0",
    frameworks: [
      { name: "Next.js", version: "16" },
      { name: "React", version: "19" },
    ],
    stack: ["Next.js 16", "React 19", "Yumma CSS 3", "Phosphor Icons"],
    version: "3.7.0",
    pages: [],
    previewUrl: "#",
    purchaseUrl: "#",
    cover: "/img/templates/placeholder.png",
    screenshots: [],
  },
  {
    slug: "oriental",
    name: "Oriental",
    tagline: "Documentation",
    description:
      "A clean documentation template for open source projects and developer tools.",
    price: 19,
    currency: "EUR",
    status: "coming-soon",
    templateVersion: "1.0.0",
    frameworks: [
      { name: "Next.js", version: "16" },
      { name: "React", version: "19" },
    ],
    stack: ["Next.js 16", "React 19", "Yumma CSS 3", "Phosphor Icons"],
    version: "3.7.0",
    pages: [],
    previewUrl: "#",
    purchaseUrl: "#",
    cover: "/img/templates/placeholder.png",
    screenshots: [],
  },
];
