/**
 * AUTO-GENERATED - do NOT edit this file manually!
 * Run: node scripts/generate-registry.mjs
 */

// ---------------------------------------------------------------------------
// Yumma UI Registry
// ---------------------------------------------------------------------------

export const registry = {
  "accordion": () => import("./ui/accordion"),
  "alert-dialog": () => import("./ui/alert-dialog"),
  "autocomplete-auto-highlight": () => import("./ui/autocomplete-auto-highlight"),
  "autocomplete-disabled": () => import("./ui/autocomplete-disabled"),
  "autocomplete-grouped": () => import("./ui/autocomplete-grouped"),
  "autocomplete-helper": () => import("./ui/autocomplete-helper"),
  "autocomplete-icon-leading": () => import("./ui/autocomplete-icon-leading"),
  "autocomplete-icon-trailing": () => import("./ui/autocomplete-icon-trailing"),
  "autocomplete-icon": () => import("./ui/autocomplete-icon"),
  "autocomplete-inset": () => import("./ui/autocomplete-inset"),
  "autocomplete-lg": () => import("./ui/autocomplete-lg"),
  "autocomplete-limit": () => import("./ui/autocomplete-limit"),
  "autocomplete-loading": () => import("./ui/autocomplete-loading"),
  "autocomplete-md": () => import("./ui/autocomplete-md"),
  "autocomplete-outset": () => import("./ui/autocomplete-outset"),
  "autocomplete-sm": () => import("./ui/autocomplete-sm"),
  "autocomplete-square": () => import("./ui/autocomplete-square"),
  "autocomplete-squircle": () => import("./ui/autocomplete-squircle"),
  "autocomplete-static": () => import("./ui/autocomplete-static"),
  "autocomplete": () => import("./ui/autocomplete"),
  "avatar-detailed": () => import("./ui/avatar-detailed"),
  "avatar-edit": () => import("./ui/avatar-edit"),
  "avatar-icon-fallback": () => import("./ui/avatar-icon-fallback"),
  "avatar-initial-fallback": () => import("./ui/avatar-initial-fallback"),
  "avatar-lg": () => import("./ui/avatar-lg"),
  "avatar-md": () => import("./ui/avatar-md"),
  "avatar-sm": () => import("./ui/avatar-sm"),
  "avatar-square": () => import("./ui/avatar-square"),
  "avatar-squircle": () => import("./ui/avatar-squircle"),
  "avatar-stack-compact": () => import("./ui/avatar-stack-compact"),
  "avatar-stacked": () => import("./ui/avatar-stacked"),
  "avatar-status": () => import("./ui/avatar-status"),
  "avatar-verified": () => import("./ui/avatar-verified"),
  "avatar": () => import("./ui/avatar"),
  "badge": () => import("./ui/badge"),
  "breadcrumb": () => import("./ui/breadcrumb"),
  "button-favorite": () => import("./ui/button-favorite"),
  "button-group-icon": () => import("./ui/button-group-icon"),
  "button-group-pill-label": () => import("./ui/button-group-pill-label"),
  "button-group-pill": () => import("./ui/button-group-pill"),
  "button-group": () => import("./ui/button-group"),
  "button-icon-leading": () => import("./ui/button-icon-leading"),
  "button-icon-trailing": () => import("./ui/button-icon-trailing"),
  "button": () => import("./ui/button"),
  "checkbox-group-label": () => import("./ui/checkbox-group-label"),
  "checkbox-group-nested-parent": () => import("./ui/checkbox-group-nested-parent"),
  "checkbox-parent": () => import("./ui/checkbox-parent"),
  "checkbox": () => import("./ui/checkbox"),
  "collapsible": () => import("./ui/collapsible"),
  "combobox-grouped": () => import("./ui/combobox-grouped"),
  "combobox-helper": () => import("./ui/combobox-helper"),
  "combobox": () => import("./ui/combobox"),
  "command-palette-description": () => import("./ui/command-palette-description"),
  "command-palette-icon-leading": () => import("./ui/command-palette-icon-leading"),
  "command-palette-icon-trailing": () => import("./ui/command-palette-icon-trailing"),
  "command-palette-inset": () => import("./ui/command-palette-inset"),
  "command-palette-minimal": () => import("./ui/command-palette-minimal"),
  "command-palette-outset": () => import("./ui/command-palette-outset"),
  "command-palette-shortcut": () => import("./ui/command-palette-shortcut"),
  "command-palette-square": () => import("./ui/command-palette-square"),
  "command-palette-squircle": () => import("./ui/command-palette-squircle"),
  "command-palette-static": () => import("./ui/command-palette-static"),
  "command-palette": () => import("./ui/command-palette"),
  "context-menu": () => import("./ui/context-menu"),
  "dialog-edit-profile": () => import("./ui/dialog-edit-profile"),
  "dialog-nested": () => import("./ui/dialog-nested"),
  "dialog-new-task": () => import("./ui/dialog-new-task"),
  "dialog-send-invite": () => import("./ui/dialog-send-invite"),
  "dialog-share-task": () => import("./ui/dialog-share-task"),
  "dialog-sign-in": () => import("./ui/dialog-sign-in"),
  "dialog-sign-up": () => import("./ui/dialog-sign-up"),
  "dialog": () => import("./ui/dialog"),
  "empty-state-actions": () => import("./ui/empty-state-actions"),
  "empty-state-filtered": () => import("./ui/empty-state-filtered"),
  "empty-state-icon": () => import("./ui/empty-state-icon"),
  "empty-state-inbox": () => import("./ui/empty-state-inbox"),
  "empty-state-inset": () => import("./ui/empty-state-inset"),
  "empty-state-outset": () => import("./ui/empty-state-outset"),
  "empty-state-search": () => import("./ui/empty-state-search"),
  "empty-state-square": () => import("./ui/empty-state-square"),
  "empty-state-squircle": () => import("./ui/empty-state-squircle"),
  "empty-state-static": () => import("./ui/empty-state-static"),
  "empty-state-text": () => import("./ui/empty-state-text"),
  "empty-state": () => import("./ui/empty-state"),
  "field-button": () => import("./ui/field-button"),
  "field-password": () => import("./ui/field-password"),
  "field-prefix": () => import("./ui/field-prefix"),
  "field-suffix": () => import("./ui/field-suffix"),
  "field": () => import("./ui/field"),
  "file-upload": () => import("./ui/file-upload"),
  "menu": () => import("./ui/menu"),
  "menubar": () => import("./ui/menubar"),
  "meter": () => import("./ui/meter"),
  "number-field": () => import("./ui/number-field"),
  "onboarding-checklist": () => import("./ui/onboarding-checklist"),
  "onboarding-dismissible": () => import("./ui/onboarding-dismissible"),
  "onboarding-icon-leading": () => import("./ui/onboarding-icon-leading"),
  "onboarding-icon-trailing": () => import("./ui/onboarding-icon-trailing"),
  "onboarding-inset": () => import("./ui/onboarding-inset"),
  "onboarding-outset": () => import("./ui/onboarding-outset"),
  "onboarding-pagination": () => import("./ui/onboarding-pagination"),
  "onboarding-progress": () => import("./ui/onboarding-progress"),
  "onboarding-square": () => import("./ui/onboarding-square"),
  "onboarding-squircle": () => import("./ui/onboarding-squircle"),
  "onboarding-static": () => import("./ui/onboarding-static"),
  "onboarding": () => import("./ui/onboarding"),
  "popover-color-palette": () => import("./ui/popover-color-palette"),
  "popover": () => import("./ui/popover"),
  "preview-card-compact": () => import("./ui/preview-card-compact"),
  "preview-card-multiple": () => import("./ui/preview-card-multiple"),
  "preview-card-project": () => import("./ui/preview-card-project"),
  "preview-card": () => import("./ui/preview-card"),
  "progress": () => import("./ui/progress"),
  "radio": () => import("./ui/radio"),
  "rating-disabled": () => import("./ui/rating-disabled"),
  "rating-emoji": () => import("./ui/rating-emoji"),
  "rating-feedback": () => import("./ui/rating-feedback"),
  "rating-inset": () => import("./ui/rating-inset"),
  "rating-outset": () => import("./ui/rating-outset"),
  "rating-readonly": () => import("./ui/rating-readonly"),
  "rating-static": () => import("./ui/rating-static"),
  "rating": () => import("./ui/rating"),
  "select-grouped": () => import("./ui/select-grouped"),
  "select": () => import("./ui/select"),
  "separator": () => import("./ui/separator"),
  "skeleton-activity": () => import("./ui/skeleton-activity"),
  "skeleton-filters": () => import("./ui/skeleton-filters"),
  "skeleton-inset": () => import("./ui/skeleton-inset"),
  "skeleton-list": () => import("./ui/skeleton-list"),
  "skeleton-outset": () => import("./ui/skeleton-outset"),
  "skeleton-static": () => import("./ui/skeleton-static"),
  "skeleton-stats": () => import("./ui/skeleton-stats"),
  "skeleton": () => import("./ui/skeleton"),
  "slider": () => import("./ui/slider"),
  "switch": () => import("./ui/switch"),
  "tabs": () => import("./ui/tabs"),
  "textarea": () => import("./ui/textarea"),
  "toggle-color-picker": () => import("./ui/toggle-color-picker"),
  "toggle-group": () => import("./ui/toggle-group"),
  "toggle": () => import("./ui/toggle"),
  "toolbar-input": () => import("./ui/toolbar-input"),
  "toolbar": () => import("./ui/toolbar"),
  "tooltip": () => import("./ui/tooltip"),
} as const;

export type RegistryId = keyof typeof registry;
export type RegistryImport = () => Promise<{ default: React.ComponentType<object> }>;

export function getRegistryImport(id: string): RegistryImport | null {
  return (registry as Record<string, RegistryImport>)[id] ?? null;
}

// ---------------------------------------------------------------------------
// Prop schemas, for components that have a real API
// ---------------------------------------------------------------------------

export interface RegistryProp {
  name: string;
  /**
   * The kind of control, not the TypeScript type. `none` covers everything a
   * JSON schema cannot offer a control for - a ReactNode, an array of objects -
   * which the props table still documents via `typeName`.
   */
  type: "enum" | "boolean" | "string" | "number" | "none";
  /** Shown in the Type column instead of `type`, when the two differ. */
  typeName?: string;
  values?: string[];
  default?: string | boolean | number;
  /**
   * A representative value for the demo, for a prop the component cannot
   * sensibly default. `default` stays the truth the props table reports.
   */
  example?: unknown;
  /**
   * An iconoir icon name, for a `ReactNode` prop that JSON cannot express.
   * Without this a component whose only visible content is an icon - Popover's
   * trigger, Toggle's face - demos itself as an empty box. The preview resolves
   * it to a real element & the usage snippet prints it as JSX plus its import,
   * so the copied code compiles. Names must exist in `EXAMPLE_ICONS` in
   * `component-preview.tsx`, a curated map rather than a dynamic lookup so the
   * bundler can still shake the icon set.
   */
  exampleIcon?: string;
  description?: string;
}

export interface RegistryMeta {
  summary?: string;
  props: RegistryProp[];
  /** Default text for components that take children. Absent means they do not. */
  children?: string;
}

export const registryMeta = {
  "accordion": () => import("./meta/accordion.json"),
  "alert-dialog": () => import("./meta/alert-dialog.json"),
  "autocomplete": () => import("./meta/autocomplete.json"),
  "avatar": () => import("./meta/avatar.json"),
  "badge": () => import("./meta/badge.json"),
  "breadcrumb": () => import("./meta/breadcrumb.json"),
  "button": () => import("./meta/button.json"),
  "checkbox": () => import("./meta/checkbox.json"),
  "collapsible": () => import("./meta/collapsible.json"),
  "combobox": () => import("./meta/combobox.json"),
  "context-menu": () => import("./meta/context-menu.json"),
  "dialog": () => import("./meta/dialog.json"),
  "field": () => import("./meta/field.json"),
  "file-upload": () => import("./meta/file-upload.json"),
  "menu": () => import("./meta/menu.json"),
  "menubar": () => import("./meta/menubar.json"),
  "meter": () => import("./meta/meter.json"),
  "number-field": () => import("./meta/number-field.json"),
  "popover": () => import("./meta/popover.json"),
  "preview-card": () => import("./meta/preview-card.json"),
  "progress": () => import("./meta/progress.json"),
  "radio": () => import("./meta/radio.json"),
  "select": () => import("./meta/select.json"),
  "separator": () => import("./meta/separator.json"),
  "skeleton": () => import("./meta/skeleton.json"),
  "slider": () => import("./meta/slider.json"),
  "switch": () => import("./meta/switch.json"),
  "tabs": () => import("./meta/tabs.json"),
  "textarea": () => import("./meta/textarea.json"),
  "toggle": () => import("./meta/toggle.json"),
  "toolbar": () => import("./meta/toolbar.json"),
  "tooltip": () => import("./meta/tooltip.json"),
} as const;

export type MetaImport = () => Promise<{ default: RegistryMeta }>;

export function getRegistryMeta(id: string): MetaImport | null {
  return (registryMeta as Record<string, MetaImport>)[id] ?? null;
}

// ---------------------------------------------------------------------------
// What `yummaui add` addresses
// ---------------------------------------------------------------------------

export interface RegistryTarget {
  component: string;
  /** `"base"` means no `--variant` flag. */
  variant: string;
}

export const registryTargets: Record<string, RegistryTarget> = {
  "accordion": { component: "accordion", variant: "base" },
  "alert-dialog": { component: "alert-dialog", variant: "base" },
  "autocomplete-auto-highlight": { component: "autocomplete", variant: "auto-highlight" },
  "autocomplete-disabled": { component: "autocomplete", variant: "disabled" },
  "autocomplete-grouped": { component: "autocomplete", variant: "grouped" },
  "autocomplete-helper": { component: "autocomplete", variant: "helper" },
  "autocomplete-icon-leading": { component: "autocomplete", variant: "icon-leading" },
  "autocomplete-icon-trailing": { component: "autocomplete", variant: "icon-trailing" },
  "autocomplete-icon": { component: "autocomplete", variant: "icon" },
  "autocomplete-inset": { component: "autocomplete", variant: "inset" },
  "autocomplete-lg": { component: "autocomplete", variant: "lg" },
  "autocomplete-limit": { component: "autocomplete", variant: "limit" },
  "autocomplete-loading": { component: "autocomplete", variant: "loading" },
  "autocomplete-md": { component: "autocomplete", variant: "md" },
  "autocomplete-outset": { component: "autocomplete", variant: "outset" },
  "autocomplete-sm": { component: "autocomplete", variant: "sm" },
  "autocomplete-square": { component: "autocomplete", variant: "square" },
  "autocomplete-squircle": { component: "autocomplete", variant: "squircle" },
  "autocomplete-static": { component: "autocomplete", variant: "static" },
  "autocomplete": { component: "autocomplete", variant: "base" },
  "avatar-detailed": { component: "avatar", variant: "detailed" },
  "avatar-edit": { component: "avatar", variant: "edit" },
  "avatar-icon-fallback": { component: "avatar", variant: "icon-fallback" },
  "avatar-initial-fallback": { component: "avatar", variant: "initial-fallback" },
  "avatar-lg": { component: "avatar", variant: "lg" },
  "avatar-md": { component: "avatar", variant: "md" },
  "avatar-sm": { component: "avatar", variant: "sm" },
  "avatar-square": { component: "avatar", variant: "square" },
  "avatar-squircle": { component: "avatar", variant: "squircle" },
  "avatar-stack-compact": { component: "avatar", variant: "stack-compact" },
  "avatar-stacked": { component: "avatar", variant: "stacked" },
  "avatar-status": { component: "avatar", variant: "status" },
  "avatar-verified": { component: "avatar", variant: "verified" },
  "avatar": { component: "avatar", variant: "base" },
  "badge": { component: "badge", variant: "base" },
  "breadcrumb": { component: "breadcrumb", variant: "base" },
  "button-favorite": { component: "button", variant: "favorite" },
  "button-group-icon": { component: "button", variant: "group-icon" },
  "button-group-pill-label": { component: "button", variant: "group-pill-label" },
  "button-group-pill": { component: "button", variant: "group-pill" },
  "button-group": { component: "button", variant: "group" },
  "button-icon-leading": { component: "button", variant: "icon-leading" },
  "button-icon-trailing": { component: "button", variant: "icon-trailing" },
  "button": { component: "button", variant: "base" },
  "checkbox-group-label": { component: "checkbox", variant: "group-label" },
  "checkbox-group-nested-parent": { component: "checkbox", variant: "group-nested-parent" },
  "checkbox-parent": { component: "checkbox", variant: "parent" },
  "checkbox": { component: "checkbox", variant: "base" },
  "collapsible": { component: "collapsible", variant: "base" },
  "combobox-grouped": { component: "combobox", variant: "grouped" },
  "combobox-helper": { component: "combobox", variant: "helper" },
  "combobox": { component: "combobox", variant: "base" },
  "command-palette-description": { component: "command-palette", variant: "description" },
  "command-palette-icon-leading": { component: "command-palette", variant: "icon-leading" },
  "command-palette-icon-trailing": { component: "command-palette", variant: "icon-trailing" },
  "command-palette-inset": { component: "command-palette", variant: "inset" },
  "command-palette-minimal": { component: "command-palette", variant: "minimal" },
  "command-palette-outset": { component: "command-palette", variant: "outset" },
  "command-palette-shortcut": { component: "command-palette", variant: "shortcut" },
  "command-palette-square": { component: "command-palette", variant: "square" },
  "command-palette-squircle": { component: "command-palette", variant: "squircle" },
  "command-palette-static": { component: "command-palette", variant: "static" },
  "command-palette": { component: "command-palette", variant: "base" },
  "context-menu": { component: "context-menu", variant: "base" },
  "dialog-edit-profile": { component: "dialog", variant: "edit-profile" },
  "dialog-nested": { component: "dialog", variant: "nested" },
  "dialog-new-task": { component: "dialog", variant: "new-task" },
  "dialog-send-invite": { component: "dialog", variant: "send-invite" },
  "dialog-share-task": { component: "dialog", variant: "share-task" },
  "dialog-sign-in": { component: "dialog", variant: "sign-in" },
  "dialog-sign-up": { component: "dialog", variant: "sign-up" },
  "dialog": { component: "dialog", variant: "base" },
  "empty-state-actions": { component: "empty-state", variant: "actions" },
  "empty-state-filtered": { component: "empty-state", variant: "filtered" },
  "empty-state-icon": { component: "empty-state", variant: "icon" },
  "empty-state-inbox": { component: "empty-state", variant: "inbox" },
  "empty-state-inset": { component: "empty-state", variant: "inset" },
  "empty-state-outset": { component: "empty-state", variant: "outset" },
  "empty-state-search": { component: "empty-state", variant: "search" },
  "empty-state-square": { component: "empty-state", variant: "square" },
  "empty-state-squircle": { component: "empty-state", variant: "squircle" },
  "empty-state-static": { component: "empty-state", variant: "static" },
  "empty-state-text": { component: "empty-state", variant: "text" },
  "empty-state": { component: "empty-state", variant: "base" },
  "field-button": { component: "field", variant: "button" },
  "field-password": { component: "field", variant: "password" },
  "field-prefix": { component: "field", variant: "prefix" },
  "field-suffix": { component: "field", variant: "suffix" },
  "field": { component: "field", variant: "base" },
  "file-upload": { component: "file-upload", variant: "base" },
  "menu": { component: "menu", variant: "base" },
  "menubar": { component: "menubar", variant: "base" },
  "meter": { component: "meter", variant: "base" },
  "number-field": { component: "number-field", variant: "base" },
  "onboarding-checklist": { component: "onboarding", variant: "checklist" },
  "onboarding-dismissible": { component: "onboarding", variant: "dismissible" },
  "onboarding-icon-leading": { component: "onboarding", variant: "icon-leading" },
  "onboarding-icon-trailing": { component: "onboarding", variant: "icon-trailing" },
  "onboarding-inset": { component: "onboarding", variant: "inset" },
  "onboarding-outset": { component: "onboarding", variant: "outset" },
  "onboarding-pagination": { component: "onboarding", variant: "pagination" },
  "onboarding-progress": { component: "onboarding", variant: "progress" },
  "onboarding-square": { component: "onboarding", variant: "square" },
  "onboarding-squircle": { component: "onboarding", variant: "squircle" },
  "onboarding-static": { component: "onboarding", variant: "static" },
  "onboarding": { component: "onboarding", variant: "base" },
  "popover-color-palette": { component: "popover", variant: "color-palette" },
  "popover": { component: "popover", variant: "base" },
  "preview-card-compact": { component: "preview-card", variant: "compact" },
  "preview-card-multiple": { component: "preview-card", variant: "multiple" },
  "preview-card-project": { component: "preview-card", variant: "project" },
  "preview-card": { component: "preview-card", variant: "base" },
  "progress": { component: "progress", variant: "base" },
  "radio": { component: "radio", variant: "base" },
  "rating-disabled": { component: "rating", variant: "disabled" },
  "rating-emoji": { component: "rating", variant: "emoji" },
  "rating-feedback": { component: "rating", variant: "feedback" },
  "rating-inset": { component: "rating", variant: "inset" },
  "rating-outset": { component: "rating", variant: "outset" },
  "rating-readonly": { component: "rating", variant: "readonly" },
  "rating-static": { component: "rating", variant: "static" },
  "rating": { component: "rating", variant: "base" },
  "select-grouped": { component: "select", variant: "grouped" },
  "select": { component: "select", variant: "base" },
  "separator": { component: "separator", variant: "base" },
  "skeleton-activity": { component: "skeleton", variant: "activity" },
  "skeleton-filters": { component: "skeleton", variant: "filters" },
  "skeleton-inset": { component: "skeleton", variant: "inset" },
  "skeleton-list": { component: "skeleton", variant: "list" },
  "skeleton-outset": { component: "skeleton", variant: "outset" },
  "skeleton-static": { component: "skeleton", variant: "static" },
  "skeleton-stats": { component: "skeleton", variant: "stats" },
  "skeleton": { component: "skeleton", variant: "base" },
  "slider": { component: "slider", variant: "base" },
  "switch": { component: "switch", variant: "base" },
  "tabs": { component: "tabs", variant: "base" },
  "textarea": { component: "textarea", variant: "base" },
  "toggle-color-picker": { component: "toggle", variant: "color-picker" },
  "toggle-group": { component: "toggle", variant: "group" },
  "toggle": { component: "toggle", variant: "base" },
  "toolbar-input": { component: "toolbar", variant: "input" },
  "toolbar": { component: "toolbar", variant: "base" },
  "tooltip": { component: "tooltip", variant: "base" },
};

export function getRegistryTarget(id: string): RegistryTarget {
  return registryTargets[id] ?? { component: id, variant: "base" };
}
