export interface SidebarSection {
  title: string;
  items: (string | { title: string; items: string[] })[];
}

export const sidebarConfig = {
  docs: [
    {
      title: "Get Started",
      items: ["philosophy", "installation", "configuration", "ide-support"],
    },
    {
      title: "Handbook",
      items: [
        "colors",
        "normalize",
        "media-queries",
        "negative-values",
        "pseudo-classes",
        "pseudo-elements",
      ],
    },
    {
      title: "Background",
      items: [
        "background-attachment",
        "background-clip",
        "background-origin",
        "background-position",
        "background-repeat",
        "background-size",
      ],
    },
    {
      title: "Border & Outline",
      items: [
        {
          title: "Border",
          items: [
            "border-collapse",
            "border-spacing",
            "border-style",
            "border-width",
            "border-top-width",
            "border-right-width",
            "border-bottom-width",
            "border-left-width",
            "border-block-width",
            "border-inline-width",
          ],
        },
        {
          title: "Outline",
          items: ["outline-offset", "outline-style", "outline-width"],
        },
      ],
    },
    {
      title: "Radius & Corner",
      items: [
        {
          title: "Border Radius",
          items: [
            "border-radius",
            "border-top-radius",
            "border-right-radius",
            "border-bottom-radius",
            "border-left-radius",
            "border-top-left-radius",
            "border-top-right-radius",
            "border-bottom-left-radius",
            "border-bottom-right-radius",
          ],
        },
        {
          title: "Corner Shapes",
          items: [
            "corner-shape",
            "corner-block-end-shape",
            "corner-block-start-shape",
            "corner-bottom-left-shape",
            "corner-bottom-right-shape",
            "corner-bottom-shape",
            "corner-end-end-shape",
            "corner-end-start-shape",
            "corner-inline-end-shape",
            "corner-inline-start-shape",
            "corner-left-shape",
            "corner-right-shape",
            "corner-start-end-shape",
            "corner-start-start-shape",
            "corner-top-left-shape",
            "corner-top-right-shape",
            "corner-top-shape",
          ],
        },
      ],
    },
    {
      title: "Box Model",
      items: [
        { title: "Aspect Ratio", items: ["aspect-ratio"] },
        {
          title: "Block Size",
          items: ["block-size", "max-block-size", "min-block-size"],
        },
        { title: "Box Sizing", items: ["box-sizing"] },
        { title: "Height", items: ["height", "max-height", "min-height"] },
        {
          title: "Inline Size",
          items: ["inline-size", "max-inline-size", "min-inline-size"],
        },
        {
          title: "Margin",
          items: [
            "margin",
            "margin-top",
            "margin-right",
            "margin-bottom",
            "margin-left",
            "margin-block",
            "margin-block-start",
            "margin-block-end",
            "margin-inline",
            "margin-inline-start",
            "margin-inline-end",
          ],
        },
        {
          title: "Padding",
          items: [
            "padding",
            "padding-top",
            "padding-right",
            "padding-bottom",
            "padding-left",
            "padding-block",
            "padding-block-start",
            "padding-block-end",
            "padding-inline",
            "padding-inline-start",
            "padding-inline-end",
          ],
        },
        { title: "Width", items: ["width", "max-width", "min-width"] },
      ],
    },
    {
      title: "Colors",
      items: [
        "accent-color",
        "background-color",
        "border-color",
        "caret-color",
        "color",
        "fill",
        "outline-color",
        "stroke",
        "text-decoration-color",
      ],
    },
    {
      title: "Effects",
      items: [
        "backdrop-blur",
        "backdrop-grayscale",
        "blur",
        "box-shadow",
        "grayscale",
        "mix-blend-mode",
        "opacity",
      ],
    },
    {
      title: "Flexbox & Grid",
      items: [
        {
          title: "Flexbox",
          items: [
            "align-content",
            "align-items",
            "align-self",
            "flex",
            "flex-basis",
            "flex-direction",
            "flex-grow",
            "flex-shrink",
            "flex-wrap",
            "justify-content",
            "justify-items",
            "justify-self",
            "order",
          ],
        },
        {
          title: "Grid",
          items: [
            "column-gap",
            "gap",
            "grid-auto-columns",
            "grid-auto-flow",
            "grid-auto-rows",
            "grid-column",
            "grid-column-end",
            "grid-column-span",
            "grid-column-start",
            "grid-row",
            "grid-row-end",
            "grid-row-span",
            "grid-row-start",
            "grid-template-columns",
            "grid-template-rows",
            "place-content",
            "place-items",
            "place-self",
            "row-gap",
          ],
        },
      ],
    },
    {
      title: "Interactivity",
      items: [
        "appearance",
        "cursor",
        "field-sizing",
        "overscroll-behavior",
        "overscroll-behavior-block",
        "overscroll-behavior-inline",
        "overscroll-behavior-x",
        "overscroll-behavior-y",
        "pointer-events",
        "resize",
        "scroll-behavior",
        "scroll-margin",
        "scroll-padding",
        "scroll-snap-align",
        "scroll-snap-stop",
        "scroll-snap-type",
        "touch-action",
        "user-select",
      ],
    },
    {
      title: "Layout",
      items: ["clear", "display", "float", "isolation", "table-layout"],
    },
    {
      title: "Positioning",
      items: [
        "bottom",
        "inset",
        "left",
        "object-fit",
        "object-position",
        "overflow",
        "overflow-x",
        "overflow-y",
        "position",
        "right",
        "top",
        "visibility",
        "z-index",
      ],
    },
    {
      title: "Transform",
      items: [
        "rotate",
        "scale",
        "skew-x",
        "skew-y",
        "skew",
        "transform-origin",
        "translate",
        "translate-x",
        "translate-y",
      ],
    },
    {
      title: "Transition",
      items: [
        "transition-delay",
        "transition-duration",
        "transition-property",
        "transition-timing-function",
      ],
    },
    {
      title: "Typography",
      items: [
        {
          title: "Fonts",
          items: ["font-family", "font-size", "font-style", "font-weight"],
        },
        {
          title: "Text",
          items: [
            "letter-spacing",
            "line-height",
            "list-style-position",
            "list-style-type",
            "overflow-wrap",
            "text-align",
            "text-decoration-line",
            "text-decoration-style",
            "text-decoration-thickness",
            "text-decoration",
            "text-indent",
            "text-orientation",
            "text-overflow",
            "text-transform",
            "text-underline-offset",
            "text-wrap",
            "vertical-align",
            "white-space",
            "word-break",
            "writing-mode",
          ],
        },
      ],
    },
  ] satisfies SidebarSection[],
  ui: [
    { title: "Get Started", items: ["installation", "customization"] },
    {
      title: "Forms",
      items: [
        "autocomplete",
        "checkbox",
        "combobox",
        "file-upload",
        "field",
        "number-field",
        "radio",
        "select",
        "slider",
        "switch",
        "textarea",
        "toggle",
      ],
    },
    {
      title: "Display",
      items: [
        "accordion",
        "avatar",
        "badge",
        "breadcrumb",
        "collapsible",
        "preview-card",
        "progress",
        "separator",
      ],
    },
    {
      title: "Interactive",
      items: ["button", "context-menu", "menu", "menubar"],
    },
    { title: "Navigation", items: ["tabs", "toolbar"] },
    {
      title: "Overlays",
      items: ["command-palette", "dialog", "popover", "tooltip"],
    },
    {
      title: "Application UI",
      items: ["empty-state", "onboarding", "rating", "skeleton"],
    },
  ] satisfies SidebarSection[],
};

export const uiPrimitives: Record<string, string> = {
  autocomplete: "combobox",
  checkbox: "checkbox",
  combobox: "combobox",
  field: "field",
  radio: "radio",
  select: "select",
  slider: "slider",
  switch: "switch",
  toggle: "toggle",
  accordion: "accordion",
  avatar: "avatar",
  collapsible: "collapsible",
  "preview-card": "preview-card",
  progress: "progress",
  separator: "separator",
  button: "button",
  "context-menu": "context-menu",
  menu: "menu",
  menubar: "menubar",
  tabs: "tabs",
  toolbar: "toolbar",
  dialog: "dialog",
  drawer: "drawer",
  popover: "popover",
  tooltip: "tooltip",
};
