// Marks and arrows are Outline; objects are Bold Duotone. See NOTES.md, "Solar icons".
export type IconStyle = "outline" | "bold-duotone";

export const EXAMPLE_ICON_STYLE: Record<string, IconStyle> = {
  AddFolderIcon: "bold-duotone",
  AddIcon: "outline",
  ArchiveIcon: "bold-duotone",
  BellIcon: "bold-duotone",
  BookmarkIcon: "bold-duotone",
  CheckIcon: "outline",
  Columns3Icon: "outline",
  CopyIcon: "bold-duotone",
  DocumentAddIcon: "bold-duotone",
  DocumentIcon: "bold-duotone",
  FileLeftIcon: "outline",
  FileRightIcon: "outline",
  FolderIcon: "bold-duotone",
  Grid2x2Icon: "outline",
  HistoryIcon: "bold-duotone",
  KeyboardIcon: "bold-duotone",
  ListIcon: "bold-duotone",
  MagnifierIcon: "outline",
  MoonIcon: "bold-duotone",
  MoveToFolderIcon: "bold-duotone",
  PaletteIcon: "bold-duotone",
  PenIcon: "bold-duotone",
  PinIcon: "bold-duotone",
  SettingsIcon: "bold-duotone",
  SortIcon: "bold-duotone",
  StarsIcon: "bold-duotone",
  SunIcon: "bold-duotone",
  TextBoldIcon: "outline",
  TextItalicIcon: "outline",
  TextUnderlineIcon: "outline",
  TrashBinTrashIcon: "bold-duotone",
};
